accounts/urls.py
from django.conf.urls import url,include
from . import views


urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'logout/$',views.LogoutView.as_view(), name='logout'),
    url(r'signUp/$',views.SignUpView.as_view(), name='signup'),
    url(r'changePassword/$',views.change_password, name='changePassword'),
    url(r'manageAccount/$', views.manage_account, name='manageAccount'),
    url(r'displayAddresses/', views.display_address, name='displayAddress'),
    url(r'deleteAddress/', views.AddressDelete.as_view(), name='deleteAddress'),
    url(r'addAddress/', views.AddressCreate.as_view(), name='addAddress'),
    url(r'updateAddress/', views.update_address, name='updateAddress'),
]

bookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
# added this
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('send_email.urls')),
    url(r'^search/', include('posts.urls', namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    posts_home,
    book_detail
)

urlpatterns = [
    url(r'^$', posts_home, name='search'),
    url(r'^(?P<id>\d+)/$', book_detail, name='book_detail'),
]

accounts/forms.py
import re

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms
from .models import User, Address


class LoginForm(forms.Form):
    nickname = forms.CharField(required=True)
    password = forms.CharField(required=True)

    class Meta:
        fields = ('nickname', 'password')
        model = User

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']

        try:
            User.objects.get(nickname=nickname)
        except User.DoesNotExist:
            raise forms.ValidationError('Sorry that user does not exist.')

        return nickname


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email_address = forms.EmailField(max_length=254, required=True)

    class Meta:
        fields = ("nickname", "email_address", 'first_name', 'last_name', "password1", "password2")
        model = User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  #might have issues with python 2

        for field_name in ['password1', 'password2']:
            self.fields[field_name].help_text = None

        self.fields["email_address"].label = "Email Address"
        self.fields["first_name"].label = "First Name"
        self.fields["last_name"].label = "Last Name"
        self.fields["password2"].label = "Password Confirmation"

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']

        if not re.search(r'^\w+$', nickname):
            raise forms.ValidationError('Nickname can only contain alphanumeric characters and underscore.')

        try:
            User.objects.get(nickname=nickname)

        except User.DoesNotExist:
            return nickname

        raise forms.ValidationError('Nickname already exists.')

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2

            raise forms.ValidationError('Password do not match!')

    def clean_email_address(self):
        email = self.cleaned_data['email_address']

        # check if email address is valid
        if not re.match('^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$', email.lower()):
            raise forms.ValidationError('Email Address is invalid format.')

        # check if email address already exits
        try:
            User.objects.get(email_address=email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError('Email Address already exists.')


class EditUserProfileForm(ModelForm):
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    nickname = forms.CharField(label='Nickname')
    email_address = forms.EmailField(label="Email Address")

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']

        # check if nickname submitted is the same as the current user online
        if nickname == self.instance.nickname:
            return nickname

        # username is different from previous, check if it already exists
        try:
            User.objects.exclude(pk=self.instance.user_id).get(nickname=nickname)
        except User.DoesNotExist:
            return nickname

        raise forms.ValidationError('Nickname already exists.')

    def clean_email_address(self):
        email_address = self.cleaned_data['email_address']

        # check if email address is missing
        if not email_address:
            raise forms.ValidationError('Email Address is missing.')

        # check if email address submitted is the same as the current user online
        if email_address == self.instance.email_address:
            return email_address

        # email address is different from previous, check if it already exits
        try:
            User.objects.exclude(pk=self.instance.user_id).get(email_address=email_address)
        except User.DoesNotExist:
            return email_address

        raise forms.ValidationError('Email Address already exists')

    class Meta:
        model = User
        fields = ['first_name', 'last_name','nickname','email_address']


class AddressForm(ModelForm):
    street_address = forms.CharField(max_length=255, label="Street Address")
    city = forms.CharField(max_length=50, label="City")
    state = forms.CharField(max_length=2, label="State")
    zip_code = forms.CharField(max_length=5, label="Zip Code")

    def clean_zip_code(self):
        zip_code = self.cleaned_data['zip_code']
        if not zip_code.isdigit():
            raise forms.ValidationError('Zip Code can only contains numbers.')

        if len(zip_code) != 5:
            raise forms.ValidationError('Zip Code must have length of 5 digits.')

        return zip_code

    def clean_state(self):
        state = self.cleaned_data['state']
        if not state.isalpha():
            raise forms.ValidationError('State can only contain letters.')

        return state

    class Meta:
        model = Address
        fields = ['street_address', 'city', 'state', 'zip_code']


class ChangePassword(forms.Form):
    current_password = forms.CharField(label='Current Password', widget=forms.PasswordInput(), required=True)
    new_password = forms.CharField(label='New Password', widget=forms.PasswordInput(), required=True)
    retyped_password = forms.CharField(label='Retype New Password', widget=forms.PasswordInput(), required=True)

    def __init__(self, data= None, user=None, *args, **kwargs):
        self.user = user
        super(ChangePassword, self).__init__(data=data, *args, **kwargs)

    def clean_current_password(self):
        current_password = self.cleaned_data['current_password']

        if not self.user.check_password(current_password):
            raise forms.ValidationError('Incorrect current password.')

        return current_password

    def clean(self):
        cleaned_data = self.cleaned_data
        new_password = self.cleaned_data['new_password']
        retyped_password = self.cleaned_data['retyped_password']

        if new_password != retyped_password:
            self.add_error('new_password', 'New password and retyped password do not match.')

        return cleaned_data

accounts/views.py
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DeleteView, CreateView, RedirectView
from .forms import EditUserProfileForm, UserCreateForm, AddressForm, LoginForm, ChangePassword
from .models import User, Address
from django.contrib import messages


#########################################################################################################
##                                   USER FUNCTIONS                                                   ##
########################################################################################################

@csrf_protect
def login_view(request):
    next = request.POST.get('next', '/')
    form = LoginForm

    if request.method == 'POST':

        username = request.POST['nickname']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        # if we have a user object, credentials correct
        if user:
            # check to see if account is active
            if user.is_active:
                # if account is active login the user and send the user back to homepage
                login(request, user)
                current_user = request.user

                # find future order list of user
                future_order_cart = FutureOrder.objects.get(
                    user_id=current_user.user_id
                )

                # set future order id into request.session
                request.session['fOrderId'] = future_order_cart.id

                # find the latest shopping cart by user
                latest_cart = Order.objects.filter(
                    user_id=current_user.user_id
                ).order_by('date_created').last()

                # create new shopping cart if latest cart has been payed
                if latest_cart.payed_order:
                    new_cart = create_shopping_cart(current_user.user_id)
                    request.session['orderId'] = new_cart.id

                # use existing shopping cart that has not been payed for
                # used when shoppers log off then log back in with preexisting shopping cart and books stored inside
                else:
                    request.session['orderId'] = latest_cart.id

                messages.success(request, 'User has successfully logged in.')

            # account is not active
            else:
                messages.error(request, 'Your account has been disabled.')

        # no user with matching credentials
        else:
            # bad login credentials were provided
            messages.error(request, 'Sorry the credentials you input, were incorrect.')

        return HttpResponseRedirect(next)

##Needs to be done
# create cart for new users or customers with previous cart already purchased
def create_shopping_cart(user_id):
    return user_id

##Needs to be done
# create a future order for new users who login in to website
def create_future_order(user_id):
    return user_id


@csrf_protect
def manage_account(request):
    online_user = request.user
    user = User.objects.get(pk=online_user.user_id)
    form = EditUserProfileForm(request.POST or None, initial={'first_name': online_user.first_name,
                                                    'last_name': online_user.last_name, 'nickname': online_user.nickname,
                                                    'email_address': online_user.email_address}, instance=request.user)

    if request.method == 'POST':
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.nickname = form.cleaned_data['nickname']
            user.email_address = form.cleaned_data['email_address']

            user.save()

            messages.success(request, 'User information changes have been successfully saved.')

            return HttpResponseRedirect(reverse('index'))

    else:
        form = EditUserProfileForm(instance=online_user)

    return render(request, "accounts/manageAccount.html", {'form': form})


class SignUpView(CreateView):
    form_class = UserCreateForm
    model = User
    template_name = "accounts/signUp.html"
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        new_user = form.save()
        messages.info(self.request, 'Thanks for registering. You may now login.')

        # after the new user is created, login the user
        new_user = authenticate(username=form.cleaned_data['nickname'], password=form.cleaned_data['password1'])
        login(self.request, new_user)

        # create a new shopping cart and add id to session
        shopping_cart = create_shopping_cart(self.request.user.user_id)
        self.request.session['orderId'] = shopping_cart.id

        # create a new future cart and add id to session
        future_cart = create_future_order(self.request.user.user_id)
        self.request.session['fOrderId'] = future_cart.id

        return super(SignUpView, self).form_valid(form)


class LogoutView(RedirectView):
    url = reverse_lazy("index")

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, 'Successfully logged out.')
        return super().get(request, *args, **kwargs) #might have issues with python 2

##Needs to be done
def change_password(request):
    return render(request,'#', {'form': form})


#########################################################################################################
##                                   ADDRESS FUNCTIONS                                                 ##
########################################################################################################

def display_address(request):
    online_user_id = request.user.user_id
    addresses = Address.objects.filter(user_id=online_user_id)
    return render(request, 'accounts/displayAddresses.html', {'addresses': addresses})

##Needs to be done
@csrf_protect
def update_address(request):
    return render(request, '#', {'form': form})


class AddressDelete(DeleteView):
    model = Address

    def get_success_url(self):
        messages.success(self.request, 'Address was successfully removed.')
        return reverse('accounts:displayAddress')

    def get_object(self):
        address_id = self.request.POST.get('addr_id')
        return get_object_or_404(Address, pk=address_id)


class AddressCreate(CreateView):
    template_name = 'accounts/addAddress.html'
    model = Address
    form_class = AddressForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(AddressCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'Address was successfully created.')
        return reverse('accounts:displayAddress')

accounts/templates/accounts/addAddress.html
{% extends 'accounts/manageAddress.html' %}
{% block title %}Add Address {% endblock %}
{% block address_title %}Add Address {% endblock %}
{% block button_name %}Add Address {% endblock %}

accounts/templates/accounts/changePasswordForm.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}Change Password {% endblock %}

{% block content %}
<div class="container">
    <h1>Change Your Password</h1>
    <p style="padding:20px"></p>
    <form method="POST" action="{% url 'accounts:changePassword' %}" class="form-horizontal" role="form">{% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2 control-label">
                    {% bootstrap_label field.label %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field field show_label=False form_group_class=None placeholder="" %}
                </div>
            </div>
            <p style="padding:10px;"></p>
        {% endfor %}

        {% buttons %}
        <div class="col-sm-offset-4 col-sm-2">
            <button type="submit" class="btn btn-md btn-primary">Change Password</button>
        </div>
        {% endbuttons %}
    </form>
    <p style="padding:25px"></p>
</div>

{% endblock %}

accounts/templates/accounts/displayAddresses.html
{% extends 'layout.html' %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}Display Addresses {% endblock %}

{% block content %}


<div class="container">
    <h2>Address</h2>
    <p style="padding:20px;"></p>
    {% for address in addresses %}
        <h3>Address {{ forloop.counter }}</h3>
        <h4>{{ address.street_address }}</h4>
        <p style="padding:3px;"></p>
        <div class="row">
            <div class="col-sm-3">
                <form action="{% url 'accounts:updateAddress' %}" method="GET" class="form-inline">
                    {% csrf_token %}
                    <input type="hidden" value="{{ address.id }}" name="addr_id">
                    <button type="submit" class="btn btn-md btn-primary">Edit Address</button>
                </form>
            </div>
            <div class="col-sm-3 col-sm-pull-1">
                <form action="{% url 'accounts:deleteAddress' %}" method="POST" class="form-inline">
                    {%  csrf_token %}
                    <input type="hidden" value="{{ address.id }}" name="addr_id">
                    <button type="submit" class="btn btn-md btn-danger">Remove Address</button>
                </form>
            </div>
        </div>
        <hr>
    {% endfor %}

    <a class="btn btn-success btn-md" href="{% url 'accounts:addAddress' %}">Add New Address</a>

    <p style="padding:25px;"></p>
</div>


{% endblock %}

accounts/templates/accounts/login.html
<form class="form-horizontal" method="POST" action="{% url 'login' %}">{% csrf_token %}
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">Sign In</h3>
        </div>
        <div class="container">
            <div class="modal-body">
                <!-- Sign In form -->
                <div class="row">
                    <div class="form-group">
                        <label for="nicknameId" class="col-sm-2" >Nickname</label>
                        <input type="text" class="col-sm-3" id="nicknameId" name="nickname" placeholder="Nickname">
                    </div>
                    <div class="form-group">
                        <label for="passwordId" class="col-sm-2" >Password</label>
                        <input type="password" class="col-sm-3" id="passwordId" name="password" placeholder="Password">
                    </div>
                    <input type="hidden" name="next" value="{{ request.path }}">
                </div>
                {% if form.errors %}
                    <p style="color:red">Invalid credentials!!!</p>
                {% endif %}
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Sign In</button>
        </div>
</form>

{% block javascript_code %}

{% if form.errors %}
    <script>
    $(function() {
      $('#modalSignIn').modal({show: true});
    });
    </script>
{% endif %}

{% endblock %}

accounts/templates/accounts/manageAccount.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}Manage Account {% endblock %}

{% block content %}


<div class="container">
    <h1>Manage Account</h1>
    <p style="padding:20px"></p>
    <form method="POST" action="" class="form-horizontal" role="form">{% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2 control-label">
                    {% bootstrap_label field.label %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field field show_label=False required=False form_group_class=None placeholder="" %}
                </div>
            </div>
            <p style="padding:10px;"></p>
        {% endfor %}

        {% buttons %}
        <div class="col-sm-offset-4 col-sm-2">
            <button type="submit" class="btn btn-md btn-primary">Save</button>
        </div>
        {% endbuttons %}
    </form>
    <p style="padding:25px"></p>
</div>

{% endblock %}

accounts/templates/accounts/manageAddress.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
<div class="container">
    <h2>{% block address_title %} {% endblock %}</h2>
    <p style="padding:20px"></p>
    <form method="POST" action="" class="form-horizontal" role="form">{% csrf_token %}

        {% for field in form %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2 control-label">
                    {% bootstrap_label field.label %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field field show_label=False form_group_class=None placeholder="" %}
                </div>
            </div>
            <p style="padding:10px;"></p>
        {% endfor %}

        {% buttons %}
        <div class="col-sm-offset-4 col-sm-2">
            <button type="submit" class="btn btn-md btn-primary">{% block button_name %}{% endblock %}</button>
        </div>
        {% endbuttons %}
    </form>
    <p style="padding:25px"></p>
</div>

{% endblock %}

accounts/templates/accounts/signUp.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block title %}Sign Up {% endblock %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <p style="padding:20px;"></p>
    <form method="POST" class="form-horizontal" role="form">{% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2 control-label">
                    {% bootstrap_label field.label %}
                </div>
                <div class="col-sm-4">
                    {% bootstrap_field field show_label=False form_group_class=None placeholder="" %}
                </div>
            </div>
            <p style="padding:10px;"></p>
        {% endfor %}

        {% buttons %}
        <div class="col-sm-offset-4 col-sm-2">
            <button type="submit" class="btn btn-md btn-primary">Sign Up</button>
        </div>
        {% endbuttons %}
    </form>
</div>
<div>
    <p style="padding:25px"></p>
</div>

{% endblock %}

accounts/templates/accounts/updateAddress.html
{% extends 'accounts/manageAddress.html' %}
{% block title %}Update Address {% endblock %}
{% block address_title %}Update Address {% endblock %}
{% block button_name %}Update Address {% endblock %}